<!DOCTYPE html><html
lang="en-US"><head><meta
charset="UTF-8"><meta
name="viewport" content="width=device-width, initial-scale=1"><link
rel="profile" href="http://gmpg.org/xfn/11"> <script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-74127232-1', 'auto',{
		'anonymizeIp': true,
		'storage': 'none',
		'storeGac': false,
		'siteSpeedSampleRate': 90
	});
	ga('require', 'autotrack');
	ga('send', 'pageview');</script> <title>Programming for failure &#8211; learning the basics &#8211; Brilliant Coding Blog</title><meta
name="robots" content="max-snippet:-1, max-image-preview:large, max-video-preview:-1"/><link
rel="canonical" href="https://brilliantcoding.com/2019/01/programming-for-failure-learning-the-basics/" /><meta
property="og:locale" content="en_US" /><meta
property="og:type" content="article" /><meta
property="og:title" content="Programming for failure - learning the basics" /><meta
property="og:description" content="When code fails, the programmer has to consider what happens when that failure occurs. That includes knowing what the failure means and how to handle it. Exception handling is the sub-program inside of the program where we, as programmers, attempt to exert some control over the results of that failure." /><meta
property="og:url" content="https://brilliantcoding.com/2019/01/programming-for-failure-learning-the-basics/" /><meta
property="og:site_name" content="Brilliant Coding Blog" /><meta
property="article:tag" content="Java" /><meta
property="article:tag" content="Python" /><meta
property="article:section" content="Software Development" /><meta
property="article:published_time" content="2019-01-19T06:53:38+00:00" /><meta
property="article:modified_time" content="2019-12-16T14:28:18+00:00" /><meta
property="og:updated_time" content="2019-12-16T14:28:18+00:00" /><meta
property="og:image" content="https://brilliantcoding.com/wp-content/uploads/2019/01/programming-for-failure-basics-socialthumb.jpg" /><meta
property="og:image:width" content="1200" /><meta
property="og:image:height" content="675" /><meta
name="twitter:card" content="summary" /><meta
name="twitter:description" content="When code fails, the programmer has to consider what happens when that failure occurs. That includes knowing what the failure means and how to handle it. Exception handling is the sub-program inside of the program where we, as programmers, attempt to exert some control over the results of that failure." /><meta
name="twitter:title" content="Programming for failure - learning the basics" /><meta
name="twitter:site" content="@brilliantcoding" /><meta
name="twitter:image" content="http://localhost:32783/wp-content/uploads/2019/01/programming-for-failure-basics-socialthumb.jpg" /><meta
name="twitter:creator" content="@brilliantcoding" /> <script type='application/ld+json' class='yoast-schema-graph yoast-schema-graph--main'>{
    "@context": "https://schema.org",
    "@graph": [
        {
            "@type": "Organization",
            "@id": "https://brilliantcoding.com/#organization",
            "name": "Brilliant Coding",
            "url": "https://brilliantcoding.com/",
            "sameAs": [
                "https://twitter.com/brilliantcoding"
            ],
            "logo": {
                "@type": "ImageObject",
                "@id": "https://brilliantcoding.com/#logo",
                "url": "https://brilliantcoding.com/wp-content/uploads/2018/01/brilliantcoding-logo.png",
                "width": 120,
                "height": 120,
                "caption": "Brilliant Coding"
            },
            "image": {
                "@id": "https://brilliantcoding.com/#logo"
            }
        },
        {
            "@type": "WebSite",
            "@id": "https://brilliantcoding.com/#website",
            "url": "https://brilliantcoding.com/",
            "name": "Brilliant Coding Blog",
            "description": "Be Brilliant",
            "publisher": {
                "@id": "https://brilliantcoding.com/#organization"
            },
            "potentialAction": {
                "@type": "SearchAction",
                "target": "https://brilliantcoding.com/?s={search_term_string}",
                "query-input": "required name=search_term_string"
            }
        },
        {
            "@type": "ImageObject",
            "@id": "https://brilliantcoding.com/2019/01/programming-for-failure-learning-the-basics/#primaryimage",
            "url": "https://brilliantcoding.com/wp-content/uploads/2019/01/error-hierarchy.png",
            "width": 787,
            "height": 611
        },
        {
            "@type": "WebPage",
            "@id": "https://brilliantcoding.com/2019/01/programming-for-failure-learning-the-basics/#webpage",
            "url": "https://brilliantcoding.com/2019/01/programming-for-failure-learning-the-basics/",
            "inLanguage": "en-US",
            "name": "",
            "isPartOf": {
                "@id": "https://brilliantcoding.com/#website"
            },
            "primaryImageOfPage": {
                "@id": "https://brilliantcoding.com/2019/01/programming-for-failure-learning-the-basics/#primaryimage"
            },
            "datePublished": "2019-01-19T06:53:38+00:00",
            "dateModified": "2019-12-16T14:28:18+00:00",
            "breadcrumb": {
                "@id": "https://brilliantcoding.com/2019/01/programming-for-failure-learning-the-basics/#breadcrumb"
            }
        },
        {
            "@type": "BreadcrumbList",
            "@id": "https://brilliantcoding.com/2019/01/programming-for-failure-learning-the-basics/#breadcrumb",
            "itemListElement": [
                {
                    "@type": "ListItem",
                    "position": 1,
                    "item": {
                        "@type": "WebPage",
                        "@id": "https://brilliantcoding.com/",
                        "url": "https://brilliantcoding.com/",
                        "name": "Home"
                    }
                },
                {
                    "@type": "ListItem",
                    "position": 2,
                    "item": {
                        "@type": "WebPage",
                        "@id": "https://brilliantcoding.com/category/software-development/",
                        "url": "https://brilliantcoding.com/category/software-development/",
                        "name": "Software Development"
                    }
                },
                {
                    "@type": "ListItem",
                    "position": 3,
                    "item": {
                        "@type": "WebPage",
                        "@id": "https://brilliantcoding.com/2019/01/programming-for-failure-learning-the-basics/",
                        "url": "https://brilliantcoding.com/2019/01/programming-for-failure-learning-the-basics/",
                        "name": "Programming for failure &#8211; learning the basics"
                    }
                }
            ]
        },
        {
            "@type": "Article",
            "@id": "https://brilliantcoding.com/2019/01/programming-for-failure-learning-the-basics/#article",
            "isPartOf": {
                "@id": "https://brilliantcoding.com/2019/01/programming-for-failure-learning-the-basics/#webpage"
            },
            "author": {
                "@id": "https://brilliantcoding.com/#/schema/person/bb992c97c32509cfb75e6f4834eedaae"
            },
            "headline": "Programming for failure &#8211; learning the basics",
            "datePublished": "2019-01-19T06:53:38+00:00",
            "dateModified": "2019-12-16T14:28:18+00:00",
            "commentCount": 0,
            "mainEntityOfPage": {
                "@id": "https://brilliantcoding.com/2019/01/programming-for-failure-learning-the-basics/#webpage"
            },
            "publisher": {
                "@id": "https://brilliantcoding.com/#organization"
            },
            "image": {
                "@id": "https://brilliantcoding.com/2019/01/programming-for-failure-learning-the-basics/#primaryimage"
            },
            "keywords": "Java,Python",
            "articleSection": "Software Development"
        },
        {
            "@type": [
                "Person"
            ],
            "@id": "https://brilliantcoding.com/#/schema/person/bb992c97c32509cfb75e6f4834eedaae",
            "name": "Matthew Jackowski",
            "image": {
                "@type": "ImageObject",
                "@id": "https://brilliantcoding.com/#authorlogo",
                "url": "http://0.gravatar.com/avatar/65b78c2dd9dc2d89bd72cc4ed922c954?s=96&d=mm&r=g",
                "caption": "Matthew Jackowski"
            },
            "sameAs": []
        }
    ]
}</script> <link
rel='dns-prefetch' href='//s.w.org' /><link
rel="alternate" type="application/rss+xml" title="Brilliant Coding Blog &raquo; Feed" href="https://brilliantcoding.com/feed/rss.xml" /><link
rel="alternate" type="application/rss+xml" title="Brilliant Coding Blog &raquo; Programming for failure &#8211; learning the basics Comments Feed" href="https://brilliantcoding.com/2019/01/programming-for-failure-learning-the-basics/feed/rss.xml" /><link
rel='stylesheet' id='bc-847cba1013f2ef83c10e8641953cb3bc-css'  href='https://brilliantcoding.com/wp-content/themes/brilliantcodingalpha/assets/css/bc.min.css' type='text/css' media='all' /> <script type='text/javascript' src='https://brilliantcoding.com/wp-content/themes/brilliantcodingalpha/assets/js/bc.min.js'></script> <meta
name="generator" content="WordPress 5.3" /><link
rel="icon" href="https://brilliantcoding.com/wp-content/uploads/2018/01/brilliantcoding-logo.png" sizes="32x32" /><link
rel="icon" href="https://brilliantcoding.com/wp-content/uploads/2018/01/brilliantcoding-logo.png" sizes="192x192" /><link
rel="apple-touch-icon-precomposed" href="https://brilliantcoding.com/wp-content/uploads/2018/01/brilliantcoding-logo.png" /><meta
name="msapplication-TileImage" content="https://brilliantcoding.com/wp-content/uploads/2018/01/brilliantcoding-logo.png" /></head><body
class="post-template-default single single-post postid-606 single-format-standard"><a
id="bc-skippy" class="sr-only sr-only-focusable" href="#content">
<span
class="bc-skiplink-text">Skip to content</span>
</a><header
class="bc-navbar nav navbar navbar-expand navbar-dark flex-column flex-md-row"><div
class="navbar-nav-scroll"><ul
class="navbar-nav d-flex align-items-center"><li
class="navbar-item">
<a
class="nav-link " href="https://brilliantcoding.com/" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Bootstrap');">
<span
class="font-weight-bold">Home</span>
</a></li><li
class="navbar-item">
<a
class="nav-link " href="https://brilliantcoding.com/now/" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Bootstrap');">
<span
class="font-weight-bold">Now</span>
</a></li><li
class="navbar-item">
<a
class="nav-link " href="https://brilliantcoding.com/about/" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Bootstrap');">
<span
class="font-weight-bold">About</span>
</a></li></ul></div><ul
class="navbar-nav flex-row ml-md-auto d-none d-md-flex"><li
class="navbar-item"><a
class="nav-link " href="https://github.com/brilliantcoding" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Bootstrap');">
<i
class="fab fa-github" aria-hidden="true"></i>
</a></li><li
class="navbar-item"><a
class="nav-link " href="https://twitter.com/brilliantcoding" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Bootstrap');">
<i
class="fab fa-twitter" aria-hidden="true"></i>
</a></li><li
class="navbar-item"><a
class="nav-link " href="https://brilliantcoding.com/feed/rss.xml" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Bootstrap');">
<i
class="fa fa-rss" aria-hidden="true"></i>
</a></li></ul></header><div
class="blog-title mt-2"><div
class="container-fluid d-flex"><div
class="row pl-5"><div>
<span
class="float-left mr-3">
<img
src="https://brilliantcoding.com/wp-content/uploads/2018/01/brilliantcoding-logo.png" />
</span></div></div><div
class="align-self-end"><h1 class="site-title">
Brilliant Coding Blog</h1><p
class="site-description mb-0">Be Brilliant</p></div></div></div><div
class="bc-content"><div
class="container-fluid">
<article
id="post-606" class="h-entry row mt-5 row flex-xl-nowrap bc-post-article"><div
id="left_gutter" class="d-none d-xl-block col-xl-1"></div><div
class="col-md-12 col-xl-9 pl-4 pr-4 pb-4"><h2 class="p-name">Programming for failure &#8211; learning the basics</h2><div
class="pl-2 bc-metadata">
<span
class="clearfix"></span>
<i
class="fa fa-user" aria-hidden="true"></i>
<a
class="p-author h-card" href="https://brilliantcoding.com/author/mjjacko/">
Matthew Jackowski		</a>
<span
class="sep"> | </span>
<i
class="fa fa-calendar" aria-hidden="true"></i>
<time
class="dt-published" datetime="2019-01-19T06:53:38+00:00">
January 19, 2019			</time>
<span
class="sep"> | </span>
<i
class="fa fa-tags" aria-hidden="true"></i>
<span
class="tag-list"><a
href="https://brilliantcoding.com/tag/java/" rel="tag">Java</a>, <a
href="https://brilliantcoding.com/tag/python/" rel="tag">Python</a></span>
<span
class="d-none">
<time
class="dt-updated" datetime="2019-12-16T14:28:18+00:00">
December 16, 2019			</time>
</span></div><div
class="e-content"><p>When code fails, the programmer has to consider what happens when that failure occurs. That includes knowing what the failure means and how to handle it. Exception handling is the sub-program inside of the program where we, as programmers, attempt to exert some control over the results of that failure.<br
/>
<span
id="more-606"></span><style type="text/css">@import url("https://brilliantcoding.com/wp-content/themes/brilliantcodingalpha/highlight/styles/solarized-dark.css");</style> <script src="https://brilliantcoding.com/wp-content/themes/brilliantcodingalpha/highlight/highlight.pack.js"></script> <script>hljs.initHighlightingOnLoad();</script> <style>@font-face {
    font-family: "Iosevka";
    src: url(https://brilliantcoding.com/wp-content/themes/brilliantcodingalpha/iosevka/iosevka-regular.ttf) format("truetype");
}</style><br
/>
Often we break program failures into two distinct types: errors and exceptions. Errors represent a significant failure in the execution of the program. In dynamic languages like Python, “errors” can include typos and other syntax problems and need to be fixed by the programmer. In compiled languages like Java, errors mean that an unrecoverable problem has occurred and the program should be allowed to crash. Exceptions, however, represent failures that we, as programmers, can anticipate. In fact we often want exceptions to happen so our program and react to the environment. We might even refer to exceptions as “operational errors”.<br
/>
Here a couple of exception examples:<br
/>
The program tries to write a file, but that file doesn’t exist, so our program needs to create it first.<br
/>
The program attempts to make a network connection, but the connection times out, so our program needs to retry the connection.</p><p>In this post we’ll examine basic exception handling concepts. It’s important to note that more advanced designs exist especially when dealing with asynchronous call execution.</p><blockquote
class="blockquote"><p>If you don&#8217;t know what errors can happen or don&#8217;t know what they mean, then your program cannot be correct except by accident.</p>
<footer
class="blockquote-footer">Joyent Production Practices <cite
title="Error Handling in Node.js"><a
href="https://www.joyent.com/node-js/production/design/errors">Error Handling in Node.js</a></cite></footer></blockquote><h3>Handling exceptions</h3><p>A well designed program will avoid having very large routines in a single file. Instead, as part of the design, it’s common to break up the program into many files. This design approach results in having a number of different calls for the program’s execution. This “call stack” is straightforward when writing code for what *should* happen, but when failures happen, this is where our design requires some deeper thought..</p><p>Let&#8217;s take an example program that makes an HTTP call to a remote site with three classes: Main, ResponseHandler, and HttpConnection. This gives us three distinct execution call levels. Exceptions can happen at any level, but all exceptions can be handled at the top of the call stack due to the lower classes passing the exception back up the call stack. Handling generic exceptions at the top of our program’s “call stack” is a great way to start our error handling design. Eventually as we run and test our program we’ll build better handling routines that need to be located close to where the exception happens.</p><p>Often we will not write our program to explicitly handle *every* possible exception, in which case we should have a way to generically deal with “Unhandled” exceptions. The most common choice is to log these exceptions to a file. This type of logging is often referred to as an “exception stack trace” and we’ll talk more about this in the next section. By doing this we can identify new or unexpected unhandled exceptions, and then we can decide if we want to added specific handlers and where the best place to handle exceptions would be.</p>
<figure
class="m-3 text-center"><img
class="figure-img img-fluid rounded" style="border: 1px solid #000;" src="https://brilliantcoding.com/wp-content/uploads/2019/01/error-hierarchy.png"><figcaption
class="figure-caption text-center">An example program where exceptions are handled or passed up the call stack</figcaption></figure><p>Let’s take a stroll through a simple program that makes an HTTP call to a remote server (you can find the full code example at the end of the post). We have all used programs that do this type of function (in fact your using one now!), this is the core of what a web browser does. But even in the simplest case, exception handling is much harder than you might think!</p><p>Our simple program has a simple call stack where the main function needs some data, so it calls a response handler, who then calls the HTTP connection class. It’s useful to note that our program execution travels “down” the call stack while our exceptions pass back “up” the same stack. At the lower level, Http Connection, can only retry the connection this only really handles low level network failures or timeouts. Depending on how frequently you are making connections, this exception often rarely happens. In this example we have an exception handler but you could also just let the exception pass up the next level in the call stack, the response handler.</p><p>At the response handler level we have a much broader set of design choices on how to deal with exceptions. For example if we get an exception parsing the data in the response, we can validate it or even send it to a different parser altogether (maybe it’s not HTML after all!). Additionally we might have logic which looks for missing or empty data, in this case we need to manually throw a new exception otherwise when we pass the data to the main function, it will *think* it has data, but in fact, it does not.</p><p>Finally we have worked our way back to the top of the call stack. At this point we should be calling a single exception handling routine, this routine handles all “unhandled” exceptions. In the case of our simple example we simply display the exception to the user.</p><p>Here&#8217;s a few more key exception design observations:<br
/>
Often it&#8217;s useful to keep the exception handler close to where the exception occurs, this is so we can pass local information to the handler that will lose scope if we wait. Another key design concept is that we only attempt to catch exceptions that we want to handle.</p><p>Sometimes programs will catch an exception, but not actually handle it. In these cases we’ll want to “repeat” (“throw” in Java and “raise” in Python) the exception so that it gets passed up the next level in the call stack.</p><p>Many languages like Java and Python have a built-in exception hierarchy. Learn this hierarchy and use it, it’ll make building the exception handling part of the program easier.</p><ul><li><a
href="https://docs.python.org/3/library/exceptions.html">Native Python exceptions</a></li><li><a
href="https://airbrake.io/blog/java-exception-handling/the-java-exception-class-hierarchy">Native Java exceptions</a></li></ul><blockquote
class="blockquote"><p>By using exception handling as part of your program, you’ll have better control of program failures and be able to prevent unexpected behavior.</p></blockquote><h3>Tracing the call stack</h3>
<figure
class="figure float-right m-3"><img
class="figure-img img-fluid rounded" style="border: 1px solid #000;" src="https://brilliantcoding.com/wp-content/uploads/2019/01/example-stack-traces.png">&nbsp;<figcaption
class="figure-caption text-right">Stack traces come in many forms!</figcaption></figure><p>Our discussion of programming for failure would not be complete without mentioning the stack trace. One common step our exception handlers should do at the top level of any call stack is to log the stack trace of the exception. A stack trace represents a “map” of the execution of our program at the time the exception happened. Stack traces aren’t pretty and are for programmers only. Without an in depth knowledge of the program, it’s easy for non programmers to make incorrect inferences based on a particular stack trace. Instead we want to log the stack trace to a file the programmer can review and at the same time display a reasonable message or action to the user.<br
/>
In many programming languages the stack trace is displayed by default. So this is one of the first design considerations for our program; But as we saw if we use exception handlers, we can catch these exceptions before they make it back to the user and instead tell the user that a problem has occurred.</p><h3>Wrapping up</h3><p>Here are some additional dos and don’ts for exception handling and stack tracing:</p><ul><li
style="list-style-type: none;"><ul><li>DO: Keep any exception handling code simple.</li><li>DO: Allow external operational exceptions to fail fast and not wait on timers.</li><li>DO: Displaying messages from exceptions is an important part of the user interface design.</li><li>DO: Make any stack trace logging configurable.</li><li>DON’T: Keep stack trace logs forever.</li><li>DON’T: Truncate the stack trace.</li><li>DON’T: Automatically email the stack traces.</li><li>DON’T: Handle errors inside of your program. Remember, errors represent a significant failure of the environment or invalid code, so by definition are irrecoverable (handle the exceptions).</li></ul></li></ul><blockquote
class="blockquote"><p>Our programs run in complex environments where many different failures can occur. As programmers, this failure should be included in the design of our program and not left to happenstance.</p></blockquote><h3>Code Examples</h3><p>Java:</p><pre><code class="java">
public class Main {
    public static void main(String[] args) {
        try {
            Object obj = parseHttpResponse.getData();
            System.out.println(obj.toString());
        } catch (Exception e) {
            ExceptionHandler.displayError(e);
        }
    }
}

class ResponseHandler {
    public static Object getData() {
        try {
            Entity entity = HttpConnection.getConnection();
            if (entity == null) {
                throw new NullEntityException();
            }
            return entity;
        } catch (HtmlParseException pe) {
            ExceptionHandler.validateHtml(pe, entity);
        }
    }
}

public class HttpConnection {
    public static final int MAXIMUM_RETRIES = 3;
    public static Entity getConnection() {

        try {
            response = Http.connect(method);
            return response;
        } catch (ConnectTimeoutException cte) {
            ExceptionHandler.connectRetry(cte, method, MAXIUM_RETRIES);
        }
    }
}
</code></pre><p>Python:</p><pre><code class="python">
class HttpConnection:
    MAXIMUM_RETRIES = 3
    def get_connection(self):
        try:
            response = http.connect(method)
            return response
        except ConnectTimeoutException as cte:
            handler.connect_retry(self, cte, method, self.MAXIMUM_RETRIES)

class HttpResponse:
    def get_data(self):
        try:
            entity = HttpConnection.get_connection()
            if entity is None:
                raise NoneEntityException('entity is none')
            return entity
        except HtmlParseException as pe:
            handler.validate_html(self, pe, entity)

def main():
    try:
        obj = HttpResponse.get_data()
        print(str(obj)
    except Exception as e:
        handler.displayError(e)

</code></pre></div></div><div
class="d-none d-xl-block col-xl-2 p-0 bc-sidebar"><h6>Categories</h6><ul
class="section"><li
class="list-item">
<a
class="list-link " href="https://brilliantcoding.com/category/code-refactor/" onclick="ga('send', 'event', 'Navbar', 'Category links', 'Bootstrap');">
<span>Code Refactor (3)						</a></li><li
class="list-item">
<a
class="list-link " href="https://brilliantcoding.com/category/programming-languages/" onclick="ga('send', 'event', 'Navbar', 'Category links', 'Bootstrap');">
<span>Programming Languages (3)						</a></li><li
class="list-item">
<a
class="list-link " href="https://brilliantcoding.com/category/software-development/" onclick="ga('send', 'event', 'Navbar', 'Category links', 'Bootstrap');">
<span>Software Development (3)						</a></li><li
class="list-item">
<a
class="list-link " href="https://brilliantcoding.com/category/open-source-software/" onclick="ga('send', 'event', 'Navbar', 'Category links', 'Bootstrap');">
<span>Open Source Software (2)						</a></li><li
class="list-item">
<a
class="list-link " href="https://brilliantcoding.com/category/developer-tools/" onclick="ga('send', 'event', 'Navbar', 'Category links', 'Bootstrap');">
<span>Developer Tools (1)						</a></li><li
class="list-item">
<a
class="list-link " href="https://brilliantcoding.com/category/notes-from-the-dev/" onclick="ga('send', 'event', 'Navbar', 'Category links', 'Bootstrap');">
<span>Notes from the Dev (1)						</a></li></ul></div>
<a
id="bc-skippy" class="sr-only sr-only-focusable" href="https://brilliantcoding.com/2019/01/programming-for-failure-learning-the-basics/">
<span
class="bc-skiplink-text">Programming for failure &#8211; learning the basics</span>
</a></article></div></div>
<footer
id="colophon" class="bc-footer" role="contentinfo"><div
class="container"><div
class="bc-social-icons"><ul
class="navbar-nav flex-row ml-md-auto d-none d-md-flex"><li
class="navbar-item"><a
class="nav-link " href="https://github.com/brilliantcoding" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Bootstrap');">
<i
class="fab fa-github" aria-hidden="true"></i>
GIthub			</a></li><li
class="navbar-item"><a
class="nav-link " href="https://twitter.com/brilliantcoding" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Bootstrap');">
<i
class="fab fa-twitter" aria-hidden="true"></i>
Twitter			</a></li><li
class="navbar-item"><a
class="nav-link " href="https://brilliantcoding.com/feed/rss.xml" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Bootstrap');">
<i
class="fa fa-rss" aria-hidden="true"></i>
RSS			</a></li></ul></div><div
class="bc-copyright">
<span>© 2018 Matthew Jackowski</span>
<span>- Powered by the <a
href="https://github.com/brilliantcoding/bc-wptheme">Brilliant Coding Wordpress Theme</a></span></div>		</div>
	</footer>
</body>
</html>